package writer

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/flylea/auto-i18n/internal/config"
	"github.com/flylea/auto-i18n/internal/types"
)

func Write(cfg *config.Config, results types.TranslateResult, keyFileMap types.KeyFileMap) error {
	outputDir := cfg.OutputDir
	if !filepath.IsAbs(outputDir) {
		cwd, _ := os.Getwd()
		outputDir = filepath.Join(cwd, outputDir)
	}

	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return fmt.Errorf("failed to create output dir: %w", err)
	}

	isJSON := cfg.Output == "json"

	for _, lang := range cfg.Languages {
		output := flattenResults(results, lang)

		var content string
		if isJSON {
			content = toJSON(output)
		} else {
			content = toTypeScript(output, lang, cfg, keyFileMap)
		}

		filename := filepath.Join(outputDir, lang+"."+cfg.Output)
		if err := os.WriteFile(filename, []byte(content), 0644); err != nil {
			return fmt.Errorf("failed to write %s: %w", filename, err)
		}
		fmt.Printf("Generated %s\n", filepath.Base(filename))
	}

	return nil
}

func flattenResults(results types.TranslateResult, lang string) map[string]string {
	output := make(map[string]string)
	for key, translations := range results {
		if trans, ok := translations[lang]; ok {
			output[key] = trans
		}
	}
	return output
}

func toJSON(flat map[string]string) string {
	nested := flatToNested(flat)
	data, _ := json.MarshalIndent(nested, "", "  ")
	return string(data)
}

func flatToNested(flat map[string]string) map[string]interface{} {
	nested := make(map[string]interface{})

	// Sort keys for deterministic output
	keys := make([]string, 0, len(flat))
	for k := range flat {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, fullKey := range keys {
		value := flat[fullKey]
		segments := strings.Split(fullKey, ".")
		cur := nested

		for i, seg := range segments {
			if i == len(segments)-1 {
				cur[seg] = value
			} else {
				if _, exists := cur[seg]; !exists {
					cur[seg] = make(map[string]interface{})
				}
				cur = cur[seg].(map[string]interface{})
			}
		}
	}

	return nested
}

func toTypeScript(flat map[string]string, lang string, cfg *config.Config, keyFileMap types.KeyFileMap) string {
	var b strings.Builder

	if cfg.WithFileComment {
		b.WriteString("/**\n")
		b.WriteString(fmt.Sprintf(" * I18n locale file: %s\n", lang))
		b.WriteString(fmt.Sprintf(" * Auto-generated by auto-i18n\n"))
		b.WriteString(fmt.Sprintf(" * Generated at: %s\n", time.Now().Format(time.RFC1123)))
		b.WriteString(" */\n")
	}

	b.WriteString("export default {\n")

	nested := flatToNested(flat)
	topLevelFileMap := buildTopLevelFileMap(keyFileMap)
	writeObject(&b, nested, 1, cfg, topLevelFileMap)

	b.WriteString("};\n")
	return b.String()
}

func buildTopLevelFileMap(keyFileMap types.KeyFileMap) map[string]map[string]bool {
	result := make(map[string]map[string]bool)
	for fullKey, files := range keyFileMap {
		topKey := strings.Split(fullKey, ".")[0]
		if result[topKey] == nil {
			result[topKey] = make(map[string]bool)
		}
		for f := range files {
			result[topKey][f] = true
		}
	}
	return result
}

func writeObject(b *strings.Builder, obj map[string]interface{}, level int, cfg *config.Config, topLevelFileMap map[string]map[string]bool) {
	indent := strings.Repeat("  ", level)
	nextIndent := strings.Repeat("  ", level+1)

	keys := make([]string, 0, len(obj))
	for k := range obj {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for i, k := range keys {
		v := obj[k]

		// Write file path comment for top-level keys
		if level == 1 && cfg.WithKeyFileComment {
			if files, ok := topLevelFileMap[k]; ok && len(files) > 0 {
				b.WriteString("\n")
				for f := range files {
					b.WriteString(fmt.Sprintf("%s// %s\n", nextIndent, f))
				}
			}
		}

		keyStr := k
		if cfg.SupportChineseKey && containsChinese(k) {
			keyStr = "'" + k + "'"
		}

		if m, ok := v.(map[string]interface{}); ok {
			b.WriteString(fmt.Sprintf("%s%s: {\n", indent, keyStr))
			writeObject(b, m, level+1, cfg, topLevelFileMap)
			if i < len(keys)-1 {
				b.WriteString(fmt.Sprintf("%s},\n", nextIndent))
			} else {
				b.WriteString(fmt.Sprintf("%s}\n", nextIndent))
			}
		} else {
			val := fmt.Sprintf("%v", v)
			val = strings.ReplaceAll(val, "'", "\\'")
			if i < len(keys)-1 {
				b.WriteString(fmt.Sprintf("%s%s: '%s',\n", indent, keyStr, val))
			} else {
				b.WriteString(fmt.Sprintf("%s%s: '%s'\n", indent, keyStr, val))
			}
		}
	}
}

func containsChinese(s string) bool {
	for _, r := range s {
		if r >= 0x4e00 && r <= 0x9fa5 {
			return true
		}
	}
	return false
}
