/**
 * I18n locale file for en-US
 * Auto-generated by auto-i18n CLI
 * Generated time: 2025/12/17 10:37:31
 */
export default {

  // playground/src/views/index.vue
  
  avatar: 'Avatar',

  // playground/src/views/index.vue
  user: 'User',

  // playground/src/views/index.vue
  name: 'Name'
};