/**
 * I18n locale file for zh-CN
 * Auto-generated by auto-i18n CLI
 * Generated time: 2025/12/17 10:37:31
 */
export default {

  // playground/src/views/index.vue
  avatar: '头像',

  // playground/src/views/index.vue
  user: '用户',

  // playground/src/views/index.vue
  name: '名称'
};