name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Build
        run: go build -o dist/auto-i18n ./cmd/auto-i18n

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/auto-i18n
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
